#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
ENV_FILE="${SCRIPT_DIR}/a6000_real.env"

if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "${ENV_FILE}"
  set +a
fi

: "${ASK2ACT_A6000_PYTHON_BIN:=python3}"
: "${ASK2ACT_A6000_HOST:=127.0.0.1}"
: "${ASK2ACT_A6000_PORT:=7862}"
: "${ASK2ACT_VLLM_BASE_URL:=http://127.0.0.1:8000/v1}"
: "${ASK2ACT_VLLM_MODEL:=mimo-vl}"
: "${ASK2ACT_DETECTOR_DEVICE:=cuda:1}"
: "${ASK2ACT_DINO_BOX_THRESHOLD:=0.38}"
: "${ASK2ACT_DINO_TEXT_THRESHOLD:=0.30}"
: "${ASK2ACT_DINO_ROTATE_CLOCKWISE_90:=1}"
: "${ASK2ACT_GEN_MAX_TOKENS:=8000}"
: "${ASK2ACT_THINK_HINT:=1}"
: "${ASK2ACT_STRETCH_TRANSPORT:=zmq}"
: "${ASK2ACT_STRETCH_ZMQ_ENDPOINT:=tcp://stretch-se3-3056.local:5557}"
: "${ASK2ACT_STRETCH_TIMEOUT_MS:=120000}"
: "${ASK2ACT_STRETCH_OBSERVE_TIMEOUT_MS:=${ASK2ACT_STRETCH_TIMEOUT_MS}}"
: "${ASK2ACT_STRETCH_EXECUTE_TIMEOUT_MS:=${ASK2ACT_STRETCH_TIMEOUT_MS}}"
: "${ASK2ACT_PIPELINE_MODE:=real_pointcloud}"
: "${ASK2ACT_REAL_ALLOW_APPROXIMATE_TOPDOWN_FALLBACK:=1}"
: "${ASK2ACT_REAL_TABLE_TOP_Z_M:=auto}"
: "${ASK2ACT_REAL_TABLE_CLEARANCE_MARGIN_M:=0.005}"
: "${ASK2ACT_REAL_OBJECT_Z_MAX_ABOVE_TABLE_M:=0.22}"
: "${ASK2ACT_GEOMETRIC_TOP_DOWN_GRASP_Z_MODE:=center}"
: "${ASK2ACT_GEOMETRIC_TOP_DOWN_GRASP_TOP_CLEARANCE_M:=0.0}"
: "${ASK2ACT_GEOMETRIC_TOP_DOWN_PREGRASP_CLEARANCE_M:=0.15}"
: "${ASK2ACT_GEOMETRIC_TOP_DOWN_POSTGRASP_LIFT_M:=0.15}"
: "${ASK2ACT_GEOMETRIC_TOP_DOWN_ENABLE_BASE_REACH_TRANSLATE:=1}"
: "${ASK2ACT_GEOMETRIC_TOP_DOWN_BASE_REACH_TRANSLATE_MAX_M:=0.16}"
: "${ASK2ACT_GEOMETRIC_TOP_DOWN_BASE_REACH_TRANSLATE_MARGIN_M:=0.02}"
: "${ASK2ACT_REAL_REPLAN_AFTER_BASE_REACH:=1}"
: "${ASK2ACT_REAL_BASE_REACH_REPLAN_MAX_ATTEMPTS:=2}"
: "${ASK2ACT_AUTO_EXECUTE_ON_RESOLVE:=1}"

export PYTHONPATH="${REPO_ROOT}${PYTHONPATH:+:${PYTHONPATH}}"
export ASK2ACT_VLLM_BASE_URL
export ASK2ACT_VLLM_MODEL
export ASK2ACT_DETECTOR_DEVICE
export ASK2ACT_DINO_BOX_THRESHOLD
export ASK2ACT_DINO_TEXT_THRESHOLD
export ASK2ACT_DINO_ROTATE_CLOCKWISE_90
export ASK2ACT_GEN_MAX_TOKENS
export ASK2ACT_THINK_HINT
export ASK2ACT_STRETCH_TRANSPORT
export ASK2ACT_STRETCH_ZMQ_ENDPOINT
export ASK2ACT_STRETCH_TIMEOUT_MS
export ASK2ACT_STRETCH_OBSERVE_TIMEOUT_MS
export ASK2ACT_STRETCH_EXECUTE_TIMEOUT_MS
export ASK2ACT_PIPELINE_MODE
export ASK2ACT_REAL_ALLOW_APPROXIMATE_TOPDOWN_FALLBACK
if [[ -n "${ASK2ACT_APPROX_GEOMETRIC_TOP_DOWN_WRIST_Z_OFFSET_M:-}" ]]; then
  export ASK2ACT_APPROX_GEOMETRIC_TOP_DOWN_WRIST_Z_OFFSET_M
fi
if [[ -n "${ASK2ACT_APPROX_GEOMETRIC_TOP_DOWN_X_CORRECTION_M:-}" ]]; then
  export ASK2ACT_APPROX_GEOMETRIC_TOP_DOWN_X_CORRECTION_M
fi
if [[ -n "${ASK2ACT_APPROX_GEOMETRIC_TOP_DOWN_Y_CORRECTION_M:-}" ]]; then
  export ASK2ACT_APPROX_GEOMETRIC_TOP_DOWN_Y_CORRECTION_M
fi
if [[ -n "${ASK2ACT_GEOMETRIC_TOP_DOWN_GRIPPER_OPEN_CMD_OVERRIDE:-}" ]]; then
  export ASK2ACT_GEOMETRIC_TOP_DOWN_GRIPPER_OPEN_CMD_OVERRIDE
fi
export ASK2ACT_REAL_TABLE_TOP_Z_M
export ASK2ACT_REAL_TABLE_CLEARANCE_MARGIN_M
export ASK2ACT_REAL_OBJECT_Z_MAX_ABOVE_TABLE_M
export ASK2ACT_GEOMETRIC_TOP_DOWN_GRASP_Z_MODE
export ASK2ACT_GEOMETRIC_TOP_DOWN_GRASP_TOP_CLEARANCE_M
export ASK2ACT_GEOMETRIC_TOP_DOWN_PREGRASP_CLEARANCE_M
export ASK2ACT_GEOMETRIC_TOP_DOWN_POSTGRASP_LIFT_M
export ASK2ACT_GEOMETRIC_TOP_DOWN_ENABLE_BASE_REACH_TRANSLATE
export ASK2ACT_GEOMETRIC_TOP_DOWN_BASE_REACH_TRANSLATE_MAX_M
export ASK2ACT_GEOMETRIC_TOP_DOWN_BASE_REACH_TRANSLATE_MARGIN_M
export ASK2ACT_REAL_REPLAN_AFTER_BASE_REACH
export ASK2ACT_REAL_BASE_REACH_REPLAN_MAX_ATTEMPTS
export ASK2ACT_AUTO_EXECUTE_ON_RESOLVE
export ASK2ACT_SESSION_RECORD_ROOT="${ASK2ACT_SESSION_RECORD_ROOT:-${SCRIPT_DIR}/artifacts/session_records}"
export ASK2ACT_HEAD_CAMERA_EXTRINSICS_PATH="${ASK2ACT_HEAD_CAMERA_EXTRINSICS_PATH:-}"
export ASK2ACT_HEAD_CAMERA_EXTRINSICS_JSON="${ASK2ACT_HEAD_CAMERA_EXTRINSICS_JSON:-}"

cd "${REPO_ROOT}"
exec "${ASK2ACT_A6000_PYTHON_BIN}" -m uvicorn services.a6000_web.server:app --host "${ASK2ACT_A6000_HOST}" --port "${ASK2ACT_A6000_PORT}"
